language: node_js
node_js: node
script: 'true'
before_install:
  - npm install -g @angular/cli
install: npm install

branches:
  only:
  - master

deploy:
  provider: heroku
  app: myApp
  api_key:
    secure: ijZIQhz1MuY3+Wr80laZOxDWBjLpWzjQ8i6zHA+Xjfv30mWbzPMthMx0kJhRpbsc44VvINdrdrlwneN81I6C7fpg3wIEkFO8pNmjRngEuqUBAtiB0V3jnEXYeJ/IqQEHsnJC0v1Gamcw38QQaZUcEmtdOgep6YxHiK2sXXU/x2t/1APZDI5pDKbMeKfM0SfumNnIaCkp8UApo8yMt9EUXqfFYGniSFJD+pg0SeAS/313Dre4FJlwyxdLgDVMEXb23qvV5savBMkV/6w+ZJX3LpGCfRi4udTueJNST/JpIvbRa2+i1b18S86H1YRIgSkivAwgjIbHBj6rZ/zRzau/0QBj7QXvUv30bcbgQOyNAEdFGo4iISzzQBYG2SkNXEqh7RDUuNWI32UaHBPx/BOPm3xXz2bmdZ/ty2URa8wNMl+yZI3UM7AfPnWE5afoZTOxywQhei8O2rQetfM4Tki0lV6HER8KJr9T/BYqCj4mMRkjVV84wHchz/ogWbbXw4hYT4WeZRN5ETb73RDtY50XoJudP+RsFFR0SbhtdLGHEaeE/iEx+0CYtT2hMfkxz/1ZXEvmoPtqWJTfsTabxk540eOpnLQMzwj+djsRkDjnD8lkbuL9NLQ3zQubEvCNHvGV+oAXAdBRXeO+7owhkh3uKnn25pn7xZYTN/RYgQHv4qE=